-- ─── The goods catalogue ─────────────────────────────────────────────────────
--
-- GENERATED from src/lib/goods.ts by scripts/generate_goods_seed.mjs. Edit the
-- seed there and re-run the script rather than editing this file, so the rows
-- the database stores and the rows the app falls back to stay identical.
--
-- Idempotent: re-running updates the catalogue in place and never touches
-- stock that the shop has since sold down, because the whole variants array is
-- replaced only on a fresh insert.

begin;

insert into public.products
  (id, slug, name, department, category, tagline, story, price_cents, compare_at_cents, variant_kind, variants, details, care, grams, hue, shade, image_url, status, vip_only, sort_order)
values
  ('g1','sanur-slip-dress','Sanur Slip Dress','womens','w-dresses','Bias-cut sand-washed silk','Cut on the bias so it moves with you rather than over you, in a sand-washed silk that reads matte in daylight and catches the light after dark. Falls to mid-calf; the strap adjusts by a full inch.',32900,null,'size','[{"code":"XS","label":"XS","stock":4},{"code":"S","label":"S","stock":11},{"code":"M","label":"M","stock":14},{"code":"L","label":"L","stock":9},{"code":"XL","label":"XL","stock":3}]'::jsonb,array['100% sand-washed mulberry silk','Bias cut, adjustable strap','Made in Denpasar, in runs of forty'],'Hand wash cold, dry flat in shade.',240,'#B4886A','#8A6244',null,'live',false,1),
  ('g2','ubud-shirt-dress','Ubud Shirt Dress','womens','w-dresses','Washed linen, belted','A long shirt with the collar left soft and the waist left to you — the belt ties, knots or comes off entirely. Washed twice before it is cut, so it arrives already broken in.',24900,null,'size','[{"code":"XS","label":"XS","stock":6},{"code":"S","label":"S","stock":12},{"code":"M","label":"M","stock":15},{"code":"L","label":"L","stock":10},{"code":"XL","label":"XL","stock":5}]'::jsonb,array['100% Belgian linen, garment washed','Self belt, side seam pockets','Mother-of-pearl buttons'],'Machine wash cold, tumble low.',320,'#C9BBA4','#9A8B72',null,'live',false,2),
  ('g3','batu-camisole','Batu Camisole','womens','w-tops','Silk, cut straight','The piece the rest of the wardrobe hangs off. Straight through the body, finished with a French seam, and long enough to stay tucked.',14900,null,'size','[{"code":"XS","label":"XS","stock":8},{"code":"S","label":"S","stock":16},{"code":"M","label":"M","stock":18},{"code":"L","label":"L","stock":12},{"code":"XL","label":"XL","stock":6}]'::jsonb,array['100% mulberry silk, 19 momme','French seams throughout','Cut long to stay tucked'],'Hand wash cold, dry flat in shade.',110,'#D9C9B4','#A8977F',null,'live',false,3),
  ('g4','canggu-open-shirt','Canggu Open Shirt','womens','w-tops','Cotton voile, sheer weave','An open-weave voile shirt to throw over everything else. Drops off the shoulder, rolls to the elbow and dries in the time it takes to cross the sand.',17900,null,'size','[{"code":"XS","label":"XS","stock":5},{"code":"S","label":"S","stock":14},{"code":"M","label":"M","stock":16},{"code":"L","label":"L","stock":11},{"code":"XL","label":"XL","stock":4}]'::jsonb,array['100% cotton voile','Dropped shoulder, curved hem','Semi-sheer — layers over swim'],'Machine wash cold, line dry.',150,'#E0D7C6','#AA9F8C',null,'live',false,4),
  ('g5','seminyak-wide-trouser','Seminyak Wide Trouser','womens','w-bottoms','Linen, elastic back','Wide from the hip with a flat front and an elastic back, so it holds a line without holding you. Hemmed to break on the top of the foot.',21900,null,'size','[{"code":"XS","label":"XS","stock":7},{"code":"S","label":"S","stock":13},{"code":"M","label":"M","stock":17},{"code":"L","label":"L","stock":10},{"code":"XL","label":"XL","stock":6}]'::jsonb,array['100% Belgian linen','Flat front, elastic back waist','Deep side pockets'],'Machine wash cold, tumble low.',300,'#B8A98F','#8B7D66',null,'live',false,5),
  ('g6','tanah-wrap-skirt','Tanah Wrap Skirt','womens','w-bottoms','Hand-blocked cotton','One length of hand-blocked cotton, one tie, no zip. Wraps to a midi on most and a maxi on some, which is the point.',16900,null,'size','[{"code":"XS","label":"XS","stock":6},{"code":"S","label":"S","stock":11},{"code":"M","label":"M","stock":13},{"code":"L","label":"L","stock":9},{"code":"XL","label":"XL","stock":4}]'::jsonb,array['Hand block-printed cotton','Single tie, no closures','Each print sits differently'],'Hand wash cold, separately for the first wash.',210,'#A87E6A','#7E5B4B',null,'live',false,6),
  ('g7','kuta-one-piece','Kuta One-Piece','womens','w-swim','Scoop back, full lining','A square neck in front, a scoop to the waist behind, and a full lining so it holds its shape wet. Built from a recycled yarn that survives chlorine and sunscreen.',18900,null,'size','[{"code":"XS","label":"XS","stock":5},{"code":"S","label":"S","stock":12},{"code":"M","label":"M","stock":14},{"code":"L","label":"L","stock":9},{"code":"XL","label":"XL","stock":5}]'::jsonb,array['78% recycled polyamide, 22% elastane','Fully lined, removable cups','UPF 50+'],'Rinse in fresh water, dry in shade.',140,'#4F6E70','#35504F',null,'live',false,7),
  ('g8','jimbaran-kaftan','Jimbaran Kaftan','womens','w-swim','One size, floor length','Floor length, split to the thigh, and cut wide enough to belong to whoever picks it up. The cover-up that goes to dinner.',19900,null,'one','[{"code":"OS","label":"One size","stock":22}]'::jsonb,array['100% cotton gauze','One size, floor length','Side splits to the thigh'],'Machine wash cold, line dry.',260,'#D4C4AD','#A08F79',null,'live',false,8),
  ('g9','amed-linen-coat','Amed Linen Coat','womens','w-outer','Unlined, wrist length','A long unlined coat for the twenty minutes a day the island is cold and the eight hours it is air-conditioned. Falls below the knee, ties at the waist.',36900,null,'size','[{"code":"XS","label":"XS","stock":3},{"code":"S","label":"S","stock":8},{"code":"M","label":"M","stock":10},{"code":"L","label":"L","stock":7},{"code":"XL","label":"XL","stock":3}]'::jsonb,array['Heavyweight Belgian linen, unlined','Self tie, patch pockets','Falls below the knee'],'Dry clean, or hand wash cold.',520,'#9E9482','#736B5C',null,'live',false,9),
  ('g10','legian-camp-shirt','Legian Camp Shirt','mens','m-shirts','Open collar, linen','The camp collar sits flat whether it is buttoned or not, which is the whole argument for one. Cut straight, hemmed to be worn out.',19900,null,'size','[{"code":"S","label":"S","stock":7},{"code":"M","label":"M","stock":15},{"code":"L","label":"L","stock":19},{"code":"XL","label":"XL","stock":13},{"code":"XXL","label":"XXL","stock":6}]'::jsonb,array['100% Belgian linen','Camp collar, single chest pocket','Straight hem, worn out'],'Machine wash cold, tumble low.',260,'#8E9A9B','#66716F',null,'live',false,10),
  ('g11','padang-gauze-shirt','Padang Gauze Shirt','mens','m-shirts','Long sleeve, open weave','An open-weave cotton gauze that moves air through it. Long in the sleeve, light enough to wear buttoned at noon.',21900,null,'size','[{"code":"S","label":"S","stock":5},{"code":"M","label":"M","stock":13},{"code":"L","label":"L","stock":16},{"code":"XL","label":"XL","stock":11},{"code":"XXL","label":"XXL","stock":5}]'::jsonb,array['100% cotton gauze, double weave','Spread collar, no pocket','Semi-sheer'],'Machine wash cold, line dry.',220,'#C7BCA8','#958B79',null,'live',false,11),
  ('g12','bukit-heavy-tee','Bukit Heavy Tee','mens','m-tees','240 gsm, boxed shoulder','Two hundred and forty grams of combed cotton, a boxed shoulder and a ribbed collar that survives the wash. Plain, and staying that way.',9900,null,'size','[{"code":"S","label":"S","stock":12},{"code":"M","label":"M","stock":24},{"code":"L","label":"L","stock":28},{"code":"XL","label":"XL","stock":19},{"code":"XXL","label":"XXL","stock":9}]'::jsonb,array['240 gsm combed cotton','Boxed shoulder, ribbed collar','Pre-shrunk'],'Machine wash cold, tumble low.',230,'#7A7468','#57524A',null,'live',false,12),
  ('g13','sidemen-knit-polo','Sidemen Knit Polo','mens','m-tees','Open-knit cotton','Knitted rather than cut and sewn, so the collar rolls instead of standing. Three buttons, open weave, dinner-appropriate on the island.',16900,null,'size','[{"code":"S","label":"S","stock":6},{"code":"M","label":"M","stock":14},{"code":"L","label":"L","stock":17},{"code":"XL","label":"XL","stock":12},{"code":"XXL","label":"XXL","stock":5}]'::jsonb,array['Open-knit Pima cotton','Three-button placket, rolled collar','Knitted panels, not cut'],'Hand wash cold, dry flat.',280,'#6E7A6B','#4E584B',null,'live',false,13),
  ('g14','uluwatu-drawstring-trouser','Uluwatu Drawstring Trouser','mens','m-bottoms','Linen, tapered','A drawstring waist that does not read as pyjamas: tapered through the leg, creased, and hemmed short of the shoe.',21900,null,'size','[{"code":"S","label":"S","stock":6},{"code":"M","label":"M","stock":14},{"code":"L","label":"L","stock":18},{"code":"XL","label":"XL","stock":12},{"code":"XXL","label":"XXL","stock":6}]'::jsonb,array['100% Belgian linen','Drawstring waist, tapered leg','Cropped at the ankle'],'Machine wash cold, tumble low.',310,'#A79C89','#7B7263',null,'live',false,14),
  ('g15','bingin-tailored-short','Bingin Tailored Short','mens','m-bottoms','Cotton twill, 7 inch','Seven inches, flat front, and a waistband that takes a belt. Short enough for the heat and cut well enough for lunch.',14900,null,'size','[{"code":"S","label":"S","stock":8},{"code":"M","label":"M","stock":16},{"code":"L","label":"L","stock":20},{"code":"XL","label":"XL","stock":14},{"code":"XXL","label":"XXL","stock":7}]'::jsonb,array['Cotton twill, garment dyed','7 inch inseam, flat front','Belt loops, slant pockets'],'Machine wash cold, tumble low.',240,'#9A8E78','#6F6656',null,'live',false,15),
  ('g16','medewi-overshirt','Medewi Overshirt','mens','m-outer','Unlined, patch pockets','A shirt heavy enough to be a jacket and light enough to stay on indoors. Four patch pockets, no lining, no structure.',27900,null,'size','[{"code":"S","label":"S","stock":4},{"code":"M","label":"M","stock":9},{"code":"L","label":"L","stock":12},{"code":"XL","label":"XL","stock":8},{"code":"XXL","label":"XXL","stock":4}]'::jsonb,array['Heavyweight linen-cotton, unlined','Four patch pockets','Corozo buttons'],'Machine wash cold, line dry.',480,'#6B6E63','#4B4E45',null,'live',false,16),
  ('g17','celuk-signet-ring','Celuk Signet Ring','jewellery','j-rings','Gold vermeil, hand-finished','A flat oval face on a tapered band, cast in Celuk and filed by hand so no two faces catch the light identically. Takes an engraving.',24900,null,'size','[{"code":"52","label":"52 · L","stock":5},{"code":"54","label":"54 · N","stock":8},{"code":"56","label":"56 · P","stock":9},{"code":"58","label":"58 · R","stock":6},{"code":"60","label":"60 · T","stock":4}]'::jsonb,array['18k gold vermeil over recycled sterling','Hand-filed face, 12 × 10 mm','Engravable — add it in the bag'],'Remove before swimming; polish with a dry cloth.',60,'#C8A063','#8A6215',null,'live',false,17),
  ('g18','tirta-stacking-band','Tirta Stacking Band','jewellery','j-rings','Hammered, 2 mm','Two millimetres of hammered gold vermeil, meant to be bought in threes and worn until the finish wears to something of your own.',11900,null,'size','[{"code":"52","label":"52 · L","stock":9},{"code":"54","label":"54 · N","stock":14},{"code":"56","label":"56 · P","stock":16},{"code":"58","label":"58 · R","stock":11},{"code":"60","label":"60 · T","stock":7}]'::jsonb,array['18k gold vermeil over recycled sterling','2 mm hammered band','Sold singly'],'Safe in fresh water; remove in the sea.',35,'#D9B98A','#8A6215',null,'live',false,18),
  ('g19','bulan-pendant','Bulan Moon Pendant','jewellery','j-necklaces','Cast disc on fine chain','A small cast disc with the surface left as it came from the mould, hung on a chain fine enough to disappear. Layers with the Riak chain below it.',18900,null,'length','[{"code":"42","label":"42 cm · Choker","stock":7},{"code":"50","label":"50 cm · Collar","stock":12},{"code":"60","label":"60 cm · Long","stock":8}]'::jsonb,array['18k gold vermeil, 16 mm disc','Fine cable chain, lobster clasp','Three lengths'],'Remove before swimming.',45,'#C8A063','#7A5A12',null,'live',false,19),
  ('g20','riak-chain','Riak Chain','jewellery','j-necklaces','Flat curb, 4 mm','A flat curb chain with enough weight to sit rather than float. Solid, not hollow, which is the difference you feel and not the one you see.',22900,null,'length','[{"code":"45","label":"45 cm","stock":6},{"code":"55","label":"55 cm","stock":10}]'::jsonb,array['18k gold vermeil over recycled sterling','Solid flat curb, 4 mm','Lobster clasp'],'Remove before swimming.',70,'#C8A063','#8A6215',null,'live',false,20),
  ('g21','ombak-hoop','Ombak Hoop','jewellery','j-earrings','Chunky, 25 mm','Twenty-five millimetres across and thick enough to read from the other side of a room, on a hinged post that actually closes.',14900,null,'one','[{"code":"PAIR","label":"Pair","stock":18}]'::jsonb,array['18k gold vermeil, 25 mm','Hinged post, sterling silver','Sold as a pair'],'Remove before swimming.',30,'#D9B98A','#8A6215',null,'live',false,21),
  ('g22','pasir-drop-earring','Pasir Drop Earring','jewellery','j-earrings','Freshwater pearl','One baroque freshwater pearl on a hand-shaped gold drop. Each pearl is its own shape, so each pair is a near match rather than a match.',16900,null,'one','[{"code":"PAIR","label":"Pair","stock":11}]'::jsonb,array['Baroque freshwater pearl, 9–11 mm','18k gold vermeil drop','Sold as a pair'],'Last on, first off; keep away from perfume.',25,'#E6DCCB','#A89880',null,'live',false,22),
  ('g23','karang-cuff','Karang Cuff','jewellery','j-bracelets','Hammered, open back','Hammered flat, opened at the back so it slides on rather than clasps. Adjusts a few millimetres with a squeeze and stays where you put it.',19900,null,'size','[{"code":"S","label":"S · 15 cm","stock":6},{"code":"M","label":"M · 17 cm","stock":10},{"code":"L","label":"L · 19 cm","stock":5}]'::jsonb,array['18k gold vermeil, 9 mm wide','Open back, adjustable','Hammered by hand'],'Remove before swimming.',65,'#C8A063','#7A5A12',null,'live',false,23),
  ('g24','kilau-lip-balm','Kilau Tinted Lip Balm','beauty','b-lips','Sheer, cocoa butter','Cocoa butter, candelilla and a little pigment. Sheer enough to apply without a mirror, which is the only balm worth carrying.',3900,null,'shade','[{"code":"BARE","label":"Bare","stock":26,"swatch":"#B4796A"},{"code":"GUAVA","label":"Guava","stock":21,"swatch":"#B4557F"},{"code":"CLAY","label":"Clay","stock":18,"swatch":"#A0553E"},{"code":"PLUM","label":"Plum","stock":14,"swatch":"#7E3B58"}]'::jsonb,array['Cocoa butter, candelilla wax, jojoba','Sheer wash of colour','4.5 g, refillable case'],'Store below 25 °C.',40,'#B4557F','#7E3B58',null,'live',false,24),
  ('g25','kilau-satin-lipstick','Kilau Satin Lipstick','beauty','b-lips','Full colour, satin finish','Four shades, no more, each one built to sit against warm skin in bright light rather than under a studio lamp. Satin, not matte — the climate decides that.',5900,null,'shade','[{"code":"TERRA","label":"Terra","stock":16,"swatch":"#A0553E"},{"code":"ROSEWOOD","label":"Rosewood","stock":19,"swatch":"#8E4A55"},{"code":"REDSALT","label":"Red Salt","stock":13,"swatch":"#A32E24"},{"code":"COCOA","label":"Cocoa","stock":11,"swatch":"#6B4A2B"}]'::jsonb,array['Satin finish, buildable','Castor and shea base','3.8 g, weighted brass case'],'Store below 25 °C.',55,'#A32E24','#6E1F18',null,'live',false,25),
  ('g26','kilau-skin-tint','Kilau Skin Tint','beauty','b-face','Sheer fluid, SPF 15','A fluid, not a foundation: it evens without covering, and it does not slide by eleven. Six shades across the range we actually see in the shop.',6900,null,'shade','[{"code":"01","label":"01 · Porcelain","stock":12,"swatch":"#B79176"},{"code":"02","label":"02 · Sand","stock":17,"swatch":"#A87E5E"},{"code":"03","label":"03 · Amber","stock":16,"swatch":"#8F6647"},{"code":"04","label":"04 · Sienna","stock":13,"swatch":"#75503A"},{"code":"05","label":"05 · Cocoa","stock":10,"swatch":"#5A3C2B"},{"code":"06","label":"06 · Ebony","stock":8,"swatch":"#432C20"}]'::jsonb,array['Sheer to medium, buildable','Mineral SPF 15','30 ml glass bottle, pump'],'Shake before use.',110,'#A87E5E','#75503A',null,'live',false,26),
  ('g27','kilau-cream-blush','Kilau Cream Blush','beauty','b-face','Cheek and lip','A cream that works on the cheek with a finger and on the lip with the same finger, which is the entire brief for a beach bag.',4900,null,'shade','[{"code":"CORAL","label":"Coral Hour","stock":20,"swatch":"#B4553E"},{"code":"FIG","label":"Fig","stock":17,"swatch":"#8E4A55"},{"code":"DUSK","label":"Dusk","stock":14,"swatch":"#7E3B58"}]'::jsonb,array['Cream-to-powder finish','Cheek and lip','6 g, refillable tin'],'Store below 25 °C.',45,'#B4553E','#82392A',null,'live',false,27),
  ('g28','kilau-kohl','Kilau Kohl Pencil','beauty','b-eyes','Waterproof, smudgeable','Soft for ninety seconds, then it stays. Waterproof enough for the sea and soft enough to smudge before it sets.',3400,null,'shade','[{"code":"INK","label":"Ink","stock":24,"swatch":"#24222A"},{"code":"EARTH","label":"Earth","stock":18,"swatch":"#4A382C"},{"code":"PALM","label":"Palm","stock":12,"swatch":"#2E4A38"}]'::jsonb,array['Waterproof, 90-second set','Retractable, no sharpener','0.3 g'],'Cap firmly after use.',25,'#4A382C','#2A1F17',null,'live',false,28),
  ('g29','kilau-eye-palette','Kilau Four-Shade Palette','beauty','b-eyes','Matte and satin, warm','Two mattes, two satins, all warm, chosen so any pair of them works. A palette you finish rather than one you keep.',7900,null,'one','[{"code":"WARM","label":"Warm neutrals","stock":15}]'::jsonb,array['Four pans, 1.4 g each','Two matte, two satin','Mirrored brass compact'],'Store below 25 °C.',95,'#A87E5E','#6E4F38',null,'live',false,29),
  ('g30','kilau-facial-oil','Kilau Facial Oil','beauty','b-skin','Kemiri and squalane','Cold-pressed kemiri — candlenut, grown an hour north of the shop — cut with squalane so it sinks instead of sitting. Four drops at night.',8900,null,'one','[{"code":"30ML","label":"30 ml","stock":19}]'::jsonb,array['Cold-pressed kemiri, squalane, rosehip','Unfragranced','30 ml amber glass, dropper'],'Keep out of direct sun.',130,'#B2762A','#7A5214',null,'live',false,30),
  ('g31','kilau-body-oil','Kilau Body Oil','beauty','b-skin','Dry-touch, lightly scented','A dry-touch oil you can dress over in two minutes, scented at a tenth of the strength of the house eau de parfum so the two can be worn together.',6900,null,'one','[{"code":"100ML","label":"100 ml","stock":22}]'::jsonb,array['Coconut, jojoba, kemiri','Dry-touch finish','100 ml glass, 1/10 fragrance load'],'Keep out of direct sun.',260,'#C8A063','#8A6215',null,'live',false,31),
  ('g32','kilau-mineral-spf','Kilau Mineral SPF 50','beauty','b-skin','Zinc, reef-safe','Non-nano zinc, no chemical filters, no white cast worth complaining about. The one piece of the range nobody here goes outside without.',5400,null,'one','[{"code":"75ML","label":"75 ml","stock":28}]'::jsonb,array['Non-nano zinc oxide, SPF 50','Reef-safe, no oxybenzone','75 ml tube'],'Reapply every two hours.',105,'#8E9A9B','#5F6C6D',null,'live',false,32),
  ('g33','kilau-surya-automatic','Surya Automatic','watches','t-automatic','38 mm, exhibition back','A 38 mm steel case around a Miyota automatic, with a sunburst dial that goes from cream to bronze as the light moves. Exhibition back, sapphire front, 100 m.',89900,null,'band','[{"code":"STEEL","label":"Steel bracelet","stock":5},{"code":"TAN","label":"Tan leather","price":84900,"stock":7},{"code":"BLACK","label":"Black leather","price":84900,"stock":6}]'::jsonb,array['Miyota 9039 automatic, 42 h reserve','38 mm steel, 10.5 mm thick','Sapphire crystal, 100 m, exhibition back'],'Rinse after sea water; service every five years.',420,'#C8A063','#6E5A3A',null,'live',false,33),
  ('g34','kilau-bulan-automatic','Bulan Automatic','watches','t-automatic','40 mm, moonphase','The one with a complication: a moonphase at six, on a lacquered dial deep enough to read as black indoors and blue outside. Forty millimetres, and no bigger.',129900,null,'band','[{"code":"STEEL","label":"Steel bracelet","stock":3},{"code":"NAVY","label":"Navy leather","price":124900,"stock":4}]'::jsonb,array['Miyota 9132 automatic, moonphase','40 mm steel, 11.8 mm thick','Sapphire crystal, 100 m'],'Rinse after sea water; service every five years.',460,'#3F5A78','#26374A',null,'live',true,34),
  ('g35','kilau-pasir-quartz','Pasir Quartz','watches','t-quartz','34 mm, slim case','Thirty-four millimetres and seven thick, which is thin enough to go under a cuff and forget. Three hands, no date, a five-year cell.',39900,null,'band','[{"code":"GOLD","label":"Gold-tone mesh","stock":9},{"code":"CREAM","label":"Cream leather","price":36900,"stock":11},{"code":"TAN","label":"Tan leather","price":36900,"stock":8}]'::jsonb,array['Ronda 762 quartz, five-year cell','34 mm case, 7 mm thick','Sapphire crystal, 50 m'],'Rinse after sea water.',260,'#D9B98A','#8A6215',null,'live',false,35),
  ('g36','kilau-ombak-quartz','Ombak Quartz','watches','t-quartz','36 mm, sector dial','A sector dial — the layout that tells the time fastest — in thirty-six millimetres of brushed steel. The watch to own if you are only owning one.',44900,null,'band','[{"code":"STEEL","label":"Steel bracelet","stock":6},{"code":"BLACK","label":"Black leather","price":41900,"stock":9}]'::jsonb,array['Ronda 763 quartz','36 mm brushed steel, 8 mm thick','Sapphire crystal, 100 m'],'Rinse after sea water.',300,'#8E9A9B','#5A6566',null,'live',false,36),
  ('g37','kilau-quick-release-strap','Quick-Release Strap','watches','t-straps','18 and 20 mm','Quick-release pins, so changing a strap is a thumbnail and ten seconds rather than a tool and a scratched lug.',8900,null,'band','[{"code":"TAN18","label":"Tan leather · 18 mm","stock":14},{"code":"TAN20","label":"Tan leather · 20 mm","stock":16},{"code":"BLACK20","label":"Black leather · 20 mm","stock":12},{"code":"CANVAS20","label":"Olive canvas · 20 mm","stock":15},{"code":"RUBBER20","label":"Black rubber · 20 mm","stock":18}]'::jsonb,array['Quick-release spring bars','18 or 20 mm lug width','Gold-tone buckle'],'Keep leather out of sea water.',60,'#A8794A','#6E4A28',null,'live',false,37)
on conflict (id) do update set
  slug = excluded.slug,
  name = excluded.name,
  department = excluded.department,
  category = excluded.category,
  tagline = excluded.tagline,
  story = excluded.story,
  price_cents = excluded.price_cents,
  compare_at_cents = excluded.compare_at_cents,
  variant_kind = excluded.variant_kind,
  details = excluded.details,
  care = excluded.care,
  grams = excluded.grams,
  hue = excluded.hue,
  shade = excluded.shade,
  status = excluded.status,
  vip_only = excluded.vip_only,
  sort_order = excluded.sort_order,
  updated_at = now();

commit;
